#INCLUDE "P16F877A.INC"		

	__CONFIG _XT_OSC & _WDT_OFF & _PWRTE_ON & _BODEN_OFF & _LVP_OFF & _CPD_OFF & _WRT_OFF & _CP_OFF

#DEFINE	DISPLAY_PORT	PORTB
#DEFINE	D1_SEL	PORTC, 0
#DEFINE	D2_SEL	PORTC, 1
#DEFINE T1 PORTA, 0
#DEFINE T2 PORTA, 1

#DEFINE LED_RED PORTD, 1
#DEFINE LED_GREEN PORTD, 2
#DEFINE BUZZER PORTD, 3
#DEFINE UPDATED UPDATE, 0
#DEFINE SWITCH PORTA, 2

	CBLOCK 0X020	
	A1, A2, A3, B1, B2, B3, BOXES,  BOXES_TEMP
	D1_VALUE, D2_VALUE,  VALUE_ON_DISPLAY
	UPDATE, MIN, MAX	
	ENDC					

	ORG		0X000				
	GOTO	MAIN
	ORG		0X004 		

	MOVF	BOXES, W
	MOVWF	BOXES_TEMP
	CALL	CONVERT_COUNTER
	CALL	SHOW_COUNTER

	BCF		INTCON, T0IF
	MOVLW	D'127'
	MOVWF	TMR0
	RETFIE								
	
MAIN
	CALL	SETUP

	BSF		INTCON, GIE
	BSF		INTCON, T0IE
	CLRF	D1_VALUE
	CLRF	D2_VALUE

	CLRF	BOXES
	CLRF	UPDATE

	MOVLW	D'0'
	MOVWF	MIN
	MOVLW	D'3'
	MOVWF	MAX

REPEAT
	BTFSC	SWITCH
	GOTO	REPEAT

	BTFSC	UPDATED
	CALL	BUZZ_AND_UPDATE

	MOVF	BOXES, W
	SUBWF	MIN, W
	BTFSC	STATUS, C
	CALL	BOXES_REACHES_MIN

	MOVF	MAX, W
	SUBWF	BOXES, W
	BTFSC	STATUS, C
	CALL	BOXES_REACHES_MAX	

	BTFSC	T1
	GOTO	CASE1
	BTFSC	T2
	GOTO	CASE2
	GOTO	REPEAT

BOXES_REACHES_MIN
	BSF		LED_RED
	BSF		BUZZER
	CALL	DELAY_500MS
	BCF		BUZZER
	BCF		LED_RED
	CALL	DELAY_500MS
	RETURN

BOXES_REACHES_MAX
	BSF		LED_GREEN
	BSF		BUZZER
	CALL	DELAY_500MS
	BCF		BUZZER
	BCF		LED_GREEN
	CALL	DELAY_500MS
	RETURN


BUZZ_AND_UPDATE
	BSF		BUZZER
	CALL	DELAY_500MS
	BCF		BUZZER
	BCF		UPDATED
	RETURN

CASE1
	BTFSS	T2
	GOTO	$-1
	BTFSC	T1
	GOTO	$-1
	BTFSC	T2
	GOTO	$-1
	INCF	BOXES, F
	BSF		UPDATED
	GOTO	REPEAT
CASE2
	BTFSS	T1
	GOTO	$-1
	BTFSC	T2
	GOTO	$-1
	BTFSC	T1
	GOTO	$-1
	DECF	BOXES, F
	BSF		UPDATED
	GOTO	REPEAT


		
CONVERT_COUNTER							
	CLRF	D1_VALUE
	CLRF	D2_VALUE
	
	MOVLW	D'10'						
	SUBWF	BOXES_TEMP, W
	BTFSS	STATUS, C				
	GOTO	$+4						
	MOVWF	BOXES_TEMP		
	INCF	D1_VALUE, F	
	GOTO	$-6	
																		
	MOVF	BOXES_TEMP, W	
	MOVWF	D2_VALUE
	RETURN


SHOW_COUNTER
	MOVF	D1_VALUE, W	
	CALL	SHOW_ON_DISPLAY		
	MOVWF	DISPLAY_PORT			
	BSF		D1_SEL		
	CALL	DELAY_5MS				
	BCF		D1_SEL

	MOVF	D2_VALUE, W	
	CALL	SHOW_ON_DISPLAY		
	MOVWF	DISPLAY_PORT			
	BSF		D2_SEL		
	CALL	DELAY_5MS				
	BCF		D2_SEL

	RETURN


SHOW_ON_DISPLAY					; THIS FUNCTION CONVERT DATA FROM DECIMAL TO 
	CLRF	DISPLAY_PORT		; CHRAR IN ORDER TO BE DISPLAYED CORRECTLY
	MOVWF	VALUE_ON_DISPLAY
	MOVF	VALUE_ON_DISPLAY, W	; IF THE VALUE IS 0 THEN 
	XORLW	D'0'
	BTFSC	STATUS, Z
	RETLW	B'00111111'				; RETURN AND PUT THIS VALUE IN W
	MOVF	VALUE_ON_DISPLAY, W
	XORLW	D'1'
	BTFSC	STATUS, Z
	RETLW	B'00000110' ;01111001'
	MOVF	VALUE_ON_DISPLAY, W
	XORLW	D'2'
	BTFSC	STATUS, Z
	RETLW	B'01011011' ;00100100'
	MOVF	VALUE_ON_DISPLAY, W
	XORLW	D'3'
	BTFSC	STATUS, Z
	RETLW	B'01001111' ;00110000'
	MOVF	VALUE_ON_DISPLAY, W
	XORLW	D'4'
	BTFSC	STATUS, Z
	RETLW	B'01100110' ;00011001'
	MOVF	VALUE_ON_DISPLAY, W
	XORLW	D'5'
	BTFSC	STATUS, Z
	RETLW	B'01101101' ;00010010'
	MOVF	VALUE_ON_DISPLAY, W
	XORLW	D'6'
	BTFSC	STATUS, Z
	RETLW	B'01111101' ;00000010'
	MOVF	VALUE_ON_DISPLAY, W
	XORLW	D'7'
	BTFSC	STATUS, Z
	RETLW	B'00000111' ;01111000'
	MOVF	VALUE_ON_DISPLAY, W
	XORLW	D'8'
	BTFSC	STATUS, Z
	RETLW	B'01111111';00000000'
	MOVF	VALUE_ON_DISPLAY, W
	XORLW	D'9'
	BTFSC	STATUS, Z
	RETLW	B'01101111' ;00010000'


DELAY_500MS
    MOVLW    D'41'
    MOVWF    A3
    MOVLW    D'167'
    MOVWF    A2
    MOVLW    D'23'
    MOVWF    A1
    DECFSZ   A1, F
    GOTO     $-1
    DECFSZ   A2, F
    GOTO     $-5
    DECFSZ   A3, F
    GOTO     $-9
    RETURN

DELAY_5MS
    MOVLW    D'1'
    MOVWF    B3
    MOVLW    D'23'
    MOVWF    B2
    MOVLW    D'71'
    MOVWF    B1
    DECFSZ   B1, F
    GOTO     $-1
    DECFSZ   B2, F
    GOTO     $-5
    DECFSZ   B3, F
    GOTO     $-9
    RETURN




SETUP
	CLRF	PORTA
	CLRF	PORTB
	CLRF	PORTC
	CLRF	PORTD
	CLRF	PORTE
	BSF 	STATUS, RP0
	MOVLW	B'00000110'
	MOVWF	ADCON0
	MOVLW	B'00000111'
	MOVWF	CMCON
	MOVLW	B'00111111'
	MOVWF	TRISA
	MOVLW	B'00000000'
	MOVWF	TRISB
	MOVLW	B'00000000'
	MOVWF	TRISC
	CLRF	TRISD
	CLRF	TRISE

	MOVLW	B'11010111'
	MOVWF	OPTION_REG
	BCF 	STATUS, RP0
	RETURN			
	END
